/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskAiRouteImport } from './routes/ask-ai'
import { Route as AutopayRouteImport } from './routes/autopay'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as PaySafeRouteImport } from './routes/pay-safe'
import { Route as SafetySwitchRouteImport } from './routes/safety-switch'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as UpiHelpRouteImport } from './routes/upi-help'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAiRoute = AskAiRouteImport.update({
  id: '/ask-ai',
  path: '/ask-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AutopayRoute = AutopayRouteImport.update({
  id: '/autopay',
  path: '/autopay',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySafeRoute = PaySafeRouteImport.update({
  id: '/pay-safe',
  path: '/pay-safe',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetySwitchRoute = SafetySwitchRouteImport.update({
  id: '/safety-switch',
  path: '/safety-switch',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const UpiHelpRoute = UpiHelpRouteImport.update({
  id: '/upi-help',
  path: '/upi-help',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask-ai': typeof AskAiRoute
  '/autopay': typeof AutopayRoute
  '/complaint': typeof ComplaintRoute
  '/complaints': typeof ComplaintsRoute
  '/pay-safe': typeof PaySafeRoute
  '/safety-switch': typeof SafetySwitchRoute
  '/transactions': typeof TransactionsRoute
  '/upi-help': typeof UpiHelpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask-ai': typeof AskAiRoute
  '/autopay': typeof AutopayRoute
  '/complaint': typeof ComplaintRoute
  '/complaints': typeof ComplaintsRoute
  '/pay-safe': typeof PaySafeRoute
  '/safety-switch': typeof SafetySwitchRoute
  '/transactions': typeof TransactionsRoute
  '/upi-help': typeof UpiHelpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask-ai': typeof AskAiRoute
  '/autopay': typeof AutopayRoute
  '/complaint': typeof ComplaintRoute
  '/complaints': typeof ComplaintsRoute
  '/pay-safe': typeof PaySafeRoute
  '/safety-switch': typeof SafetySwitchRoute
  '/transactions': typeof TransactionsRoute
  '/upi-help': typeof UpiHelpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask-ai'
    | '/autopay'
    | '/complaint'
    | '/complaints'
    | '/pay-safe'
    | '/safety-switch'
    | '/transactions'
    | '/upi-help'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask-ai'
    | '/autopay'
    | '/complaint'
    | '/complaints'
    | '/pay-safe'
    | '/safety-switch'
    | '/transactions'
    | '/upi-help'
  id:
    | '__root__'
    | '/'
    | '/ask-ai'
    | '/autopay'
    | '/complaint'
    | '/complaints'
    | '/pay-safe'
    | '/safety-switch'
    | '/transactions'
    | '/upi-help'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskAiRoute: typeof AskAiRoute
  AutopayRoute: typeof AutopayRoute
  ComplaintRoute: typeof ComplaintRoute
  ComplaintsRoute: typeof ComplaintsRoute
  PaySafeRoute: typeof PaySafeRoute
  SafetySwitchRoute: typeof SafetySwitchRoute
  TransactionsRoute: typeof TransactionsRoute
  UpiHelpRoute: typeof UpiHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-ai': {
      id: '/ask-ai'
      path: '/ask-ai'
      fullPath: '/ask-ai'
      preLoaderRoute: typeof AskAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autopay': {
      id: '/autopay'
      path: '/autopay'
      fullPath: '/autopay'
      preLoaderRoute: typeof AutopayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-safe': {
      id: '/pay-safe'
      path: '/pay-safe'
      fullPath: '/pay-safe'
      preLoaderRoute: typeof PaySafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-switch': {
      id: '/safety-switch'
      path: '/safety-switch'
      fullPath: '/safety-switch'
      preLoaderRoute: typeof SafetySwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upi-help': {
      id: '/upi-help'
      path: '/upi-help'
      fullPath: '/upi-help'
      preLoaderRoute: typeof UpiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskAiRoute: AskAiRoute,
  AutopayRoute: AutopayRoute,
  ComplaintRoute: ComplaintRoute,
  ComplaintsRoute: ComplaintsRoute,
  PaySafeRoute: PaySafeRoute,
  SafetySwitchRoute: SafetySwitchRoute,
  TransactionsRoute: TransactionsRoute,
  UpiHelpRoute: UpiHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
